import Link from 'next/link';
import RevealAnimation from '../animation/RevealAnimation';

const TermsConditionContent = () => {
  return (
    <section className="pt-32 pb-14 sm:pt-36 md:pt-42 md:pb-16 lg:pb-[88px] xl:pt-[180px] xl:pb-[200px]">
      <div className="main-container">
        <RevealAnimation delay={0.3}>
          <div className="space-y-3">
            <h2>Terms &amp; conditions</h2>
            <div className="space-y-7">
              <p>
                This site, nativpost.com (hereafter referred to as NativPost, site, or website) is owned and operated by
                AppexNexis LTD (hereafter referred to as AppexNexis, we, or company).
              </p>
              <p>
                Please carefully read, review, and understand our Terms and Conditions before using any services or
                products from nativpost.com or app.nativpost.com. Your access to and use of this website and its
                products indicate that you accept and agree to be bound by these terms and conditions.
              </p>
              <p>
                If you do not agree with these terms, you should leave the site immediately and not use any of the
                materials or services available here.
              </p>
            </div>
          </div>
        </RevealAnimation>
        <article className="terms-conditions-body">
          <RevealAnimation delay={0.4}>
            <div className="space-y-6">
              <h3>1. Limitation of liability</h3>
              <p>
                Under no circumstances shall AppexNexis LTD or NativPost be liable for any direct, indirect, incidental,
                special, or consequential damages, including but not limited to loss of data, profits, or business
                interruption, arising out of the use, or inability to use, the materials or services on this site, even
                if NativPost or an authorized representative has been advised of the possibility of such damages.
              </p>
              <p>
                NativPost generates content suggestions based on your Brand Profile and preferences. While we strive for
                the highest quality, all content passes through an approval workflow before publishing. You are
                responsible for reviewing and approving all content before it is published to your social media accounts.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.5}>
            <div className="space-y-6">
              <h3>2. Service description &amp; license</h3>
              <p>
                NativPost is a subscription-based social media content creation and management platform. Each
                subscription grants access to content generation, scheduling, publishing, and analytics features based on
                your selected plan tier (Starter, Growth, Pro, or Agency).
              </p>
              <p>
                Your subscription is tied to a single organization. You may not share login credentials or provide
                access to unauthorized users. Agency and Enterprise plans permit multi-brand management as described in
                the respective plan documentation.
              </p>
              <p>
                Content generated by NativPost for your brand is owned by you upon approval and publishing. NativPost
                retains no rights to your published content. However, NativPost may use anonymized, aggregated usage data
                to improve its services.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.6}>
            <div className="space-y-6">
              <h3>3. Ownership and intellectual property</h3>
              <p>
                The NativPost platform, including its software, design, Brand Profile system, content engine, anti-slop
                filter technology, and all associated materials remain the intellectual property of AppexNexis LTD. You
                may not claim ownership of the platform, its technology, or its processes, whether modified or
                unmodified.
              </p>
              <p>
                Our services are provided &quot;as is&quot; without warranty of any kind, expressed or implied.
                AppexNexis LTD is not liable for any losses or damages resulting from the use or inability to use
                NativPost services.
              </p>
              <p>
                User accounts and subscriptions are
                <strong className="!text-secondary dark:!text-accent font-bold"> non-transferable</strong>. For agencies
                managing client accounts: each client organization requires its own subscription if they require direct
                platform access.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.3}>
            <div className="space-y-6">
              <h3>4. Social media account access</h3>
              <p>
                By connecting your social media accounts (Instagram, Facebook, LinkedIn, X/Twitter, TikTok) to
                NativPost, you grant NativPost permission to publish approved content on your behalf. NativPost will
                never publish content without your explicit approval through the approval dashboard.
              </p>
              <p>
                You may disconnect any social media account at any time from your dashboard. NativPost stores your
                platform access tokens securely using encryption at rest and does not share them with third parties.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.4}>
            <div className="space-y-6">
              <h3>5. Refund policy</h3>
              <p>
                We believe you&apos;ll love NativPost! Still, if you&apos;re not satisfied, we offer a 14-day
                no-questions-asked refund policy. Simply contact our support team within 14 days of your original
                purchase, and we&apos;ll issue a full refund. Setup fees are non-refundable after the Brand Profile
                onboarding workshop has been completed.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.5}>
            <Link
              href="/refund-policy"
              className="section-button btn dark:btn-accent hover:btn-primary btn-xl btn-secondary">
              <span>Learn more about our refund policy</span>
            </Link>
          </RevealAnimation>
          <RevealAnimation delay={0.6}>
            <div className="space-y-6">
              <h3>6. Warranty</h3>
              <p>
                NativPost services are provided without any warranty, either expressed or implied. We do not guarantee
                specific engagement rates, follower growth, or business outcomes from content published through our
                platform. Content quality is optimized through your Brand Profile and our anti-slop filter, but results
                vary based on industry, audience, and platform algorithms.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.3}>
            <div className="space-y-6">
              <h3>7. Account termination and suspension</h3>
              <p>
                NativPost reserves the right to suspend or terminate any user account without prior notice for reasons
                including but not limited to
              </p>
              <ul>
                <li>Publishing content that violates platform community guidelines through NativPost</li>
                <li>Abusive, defamatory, or malicious behavior towards NativPost staff or other users</li>
                <li>Attempting to reverse-engineer the content engine, anti-slop filter, or Brand Profile system</li>
                <li>Using NativPost to generate spam, misleading content, or content that promotes illegal activities</li>
                <li>Sharing account credentials or unauthorized resale of NativPost services</li>
                <li>Non-payment or repeated failed payment attempts</li>
              </ul>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.4}>
            <div className="space-y-6">
              <h3>8. Privacy policy</h3>
              <p>
                We value your privacy. NativPost does not sell, rent, or share your personal information with third
                parties. Your data is used solely for purposes such as
              </p>
              <ul>
                <li>Content generation and Brand Profile management</li>
                <li>Order processing and subscription billing</li>
                <li>Account management and customer support</li>
                <li>Platform analytics and performance tracking</li>
                <li>Legal compliance and fraud prevention</li>
              </ul>
              <p>
                By using NativPost services, you consent to the collection and use of your data as described in our
                Privacy Policy.
              </p>
            </div>
          </RevealAnimation>
          <RevealAnimation delay={0.5}>
            <Link
              href="/privacy-policy"
              className="section-button btn btn-xl dark:btn-accent hover:btn-primary btn-secondary">
              <span>Read our detailed privacy policy</span>
            </Link>
          </RevealAnimation>
        </article>
      </div>
    </section>
  );
};

export default TermsConditionContent;
