// ============================================================
// MSI ADD-ONS (marketing) — src/data/msi-addons.ts
//
// Marketing mirror of the app catalog (NativPost-app/src/lib/msi/addons.ts).
// Drives the /managed positioning page. "who" = who performs the work, the one
// thing an add-on changes on top of the shared infrastructure.
// ============================================================

export type AddonWho = 'Automated' | 'AI' | 'AI + Human' | 'Operator';
export type AddonStatus = 'Live' | 'Coming soon';

export interface MsiAddonMarketing {
  id: string;
  name: string;
  tagline: string;
  description: string;
  who: AddonWho;
  priceFrom: string;
  status: AddonStatus;
  // ns-shape icon-font class.
  icon: string;
}

// The core platform — what MSI is before any add-on.
export const MSI_CORE: MsiAddonMarketing[] = [
  {
    id: 'managed_accounts',
    name: 'Managed Accounts',
    tagline: 'Real accounts, created and warmed in your target market.',
    description:
      'We create genuine, brand-owned accounts in the country you want to reach and warm them in your niche. Owned by you, operated by us.',
    who: 'Operator',
    priceFrom: '$80/account / mo',
    status: 'Live',
    icon: 'ns-shape-3',
  },
  {
    id: 'managed_publishing',
    name: 'Managed Publishing',
    tagline: 'Usage-based publishing to your managed accounts.',
    description:
      'Publish to your managed accounts from the same dashboard as your own profiles, billed per post. Human review before anything goes live.',
    who: 'AI + Human',
    priceFrom: '$1.50 / post',
    status: 'Live',
    icon: 'ns-shape-12',
  },
];

// The add-ons — activate whichever you need on top of the core.
export const MSI_ADDONS: MsiAddonMarketing[] = [
  {
    id: 'managed_posting',
    name: 'Managed Posting',
    tagline: 'We create and publish your posts, end to end.',
    description:
      'Hand off posting entirely. Our team drafts, reviews, schedules, and publishes to your accounts. You approve; we run it.',
    who: 'AI + Human',
    priceFrom: '$49 / mo',
    status: 'Coming soon',
    icon: 'ns-shape-9',
  },
  {
    id: 'managed_content',
    name: 'Managed Content',
    tagline: 'A monthly content studio: graphics, video, and copy.',
    description:
      'Submit your brand and product; get a month of on-brand graphics, edited video, and copy, reviewed by a human and scheduled for you.',
    who: 'AI + Human',
    priceFrom: '$149 / mo',
    status: 'Coming soon',
    icon: 'ns-shape-5',
  },
  {
    id: 'managed_ads',
    name: 'Managed Advertising',
    tagline: 'We build, launch, and monitor your paid campaigns.',
    description:
      'Operators configure the campaign, audience, budget, pixel, creative, copy, and tracking, then monitor it. You pay the ad platform directly for spend.',
    who: 'Operator',
    priceFrom: '$49 setup + 10–20% of spend',
    status: 'Coming soon',
    icon: 'ns-shape-16',
  },
  {
    id: 'managed_analytics',
    name: 'Managed Analytics & Strategy',
    tagline: 'A monthly growth report with next month’s plan.',
    description:
      'Winning and losing posts, competitor context, and a recommended plan each month. Generated by AI, reviewed by a human.',
    who: 'AI + Human',
    priceFrom: '$39 / mo',
    status: 'Coming soon',
    icon: 'ns-shape-21',
  },
  {
    id: 'managed_expansion',
    name: 'Managed Expansion',
    tagline: 'Scale from a few accounts to many, in one click.',
    description:
      'Provision additional managed accounts across markets on demand. A growth motion on the core, not a new product.',
    who: 'Automated',
    priceFrom: '$80/account / mo',
    status: 'Coming soon',
    icon: 'ns-shape-7',
  },
  {
    id: 'managed_community',
    name: 'Managed Community',
    tagline: 'We reply to comments and DMs, hide spam, and moderate.',
    description:
      'Operators handle inbound from one dashboard: reply to comments and DMs, hide spam, pin comments — keeping your community warm.',
    who: 'Operator',
    priceFrom: '$79 / mo',
    status: 'Coming soon',
    icon: 'ns-shape-11',
  },
  {
    id: 'managed_ugc',
    name: 'Managed UGC',
    tagline: 'AI or real creators produce short-form video.',
    description:
      'Send a product; get TikToks, Reels, and Shorts back — from AI creators or, on request, real creators.',
    who: 'AI + Human',
    priceFrom: '$25 / video',
    status: 'Coming soon',
    icon: 'ns-shape-14',
  },
  {
    id: 'managed_recovery',
    name: 'Account Recovery & Compliance',
    tagline: 'Best-effort appeal preparation and guided recovery.',
    description:
      'When an account is disabled, restricted, or shadowbanned, our operators prepare appeals and guide verification. Best-effort — the platform decides the outcome.',
    who: 'Operator',
    priceFrom: '$99 / case',
    status: 'Coming soon',
    icon: 'ns-shape-19',
  },
];
